#include <gtk/gtk.h>

char *css =
"@define-color BACKGROUND rgb(10%,10%,10%);\n"
"@define-color OFF_WHITE rgb(90%,90%,90%);\n"
"@define-color BOX_ON rgb(0%,50%,0%);\n"
"@define-color BOX_OFF rgb(20%,20%,20%);\n"
"@define-color TEXT_A rgb(92%,61%,50%);\n"
"@define-color TEXT_B rgb(64%,80%,82%);\n"
"@define-color TEXT_C rgb(90%,90%,90%);\n"
"@define-color WARNING rgb(85%,27%,27%);\n"
"@define-color DARK_LINES rgb(30%,30%,30%);\n"
"@define-color DARK_TEXT rgb(70%,70%,70%);\n"
"@define-color INFO_ON rgb(15%,58%,60%);\n"
"@define-color INFO_OFF rgb(20%,20%,20%);\n"
"@define-color BLACK rgb(0%,0%,0%);\n"
"@define-color DARK_GREEN rgb(0%,40%,0%);\n"
"@define-color DARK_RED rgb(70%,22%,22%);\n"
"@define-color DARK_TEAL rgb(12%,48%,50%);\n"
"#receiver-window {\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: @BLACK;\n"
"}\n"
"#vfo-a-text {\n"
"    font-family: FreeSans;\n"
"    color: @TEXT_B;\n"
"}\n"
"#frequency-a-text {\n"
"    font-family: FreeSans;\n"
"    font-size: 28px;\n"
"    color: @TEXT_B;\n"
"}\n"
"#vfo-b-text {\n"
"    font-family: FreeSans;\n"
"    color: @TEXT_C;\n"
"}\n"
"#frequency-b-text {\n"
"    font-family: FreeSans;\n"
"    font-size: 21px;\n"
"    color: @TEXT_C;\n"
"}\n"
"#vfo-button {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_LINES;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_OFF;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"}\n"
"#vfo-toggle {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_LINES;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_OFF;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"}\n"
"#vfo-toggle:checked {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_GREEN;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_ON;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"}\n"
"#vfo-mode-filter-button {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_GREEN;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_ON;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"}\n"
"#info-button {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_LINES;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_OFF;\n"
"    color: @INFO_OFF;\n"
"    box-shadow: none;\n"
"}\n"
"#info-button:checked {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_GREEN;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_ON;\n"
"    color: @INFO_ON;\n"
"    box-shadow: none;\n"
"}\n"
"#rit-value {\n"
"    font-family: FreeSans;\n"
"    color: @OFF_WHITE;\n"
"}\n"
"#xit-value {\n"
"    font-family: FreeSans;\n"
"    color: @OFF_WHITE;\n"
"}\n"
"#afgain-text {\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: @OFF_WHITE;\n"
"}\n"
"#afgain-scale trough {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"    box-shadow: none;\n"
"}\n"
"#afgain-scale trough block.filled {\n"
"    border-color: @TEXT_B;\n"
"}\n"
"#agcgain-text {\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: @OFF_WHITE;\n"
"}\n"
"#agcgain-scale trough {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"    box-shadow: none;\n"
"}\n"
"#agcgain-scale trough block.filled {\n"
"    background-color: @TEXT_C;\n"
"    border-color: @OFF_WHITE;\n"
"}\n"
"#info-warning {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_LINES;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_OFF;\n"
"    color: @INFO_OFF;\n"
"    box-shadow: none;\n"
"}\n"
"#info-warning:checked {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_RED;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @WARNING;\n"
"    color: @INFO_ON;\n"
"    box-shadow: none;\n"
"}\n"
"#transmit-warning {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_LINES;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_OFF;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"}\n"
"#transmit-warning:checked {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_RED;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @WARNING;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"}\n"
"#modern-slider {\n"
"    padding: 5px;\n"
"    background-image: none;\n"
"}\n"
"#modern-slider trough {\n"
"    background-color: @DARK_LINES;\n"
"    border-radius: 5px;\n"
"    min-height: 8px;\n"
"}\n"
"#modern-slider slider {\n"
"    background-color: @OFF_WHITE;\n"
"    border: 2px solid @DARK_GREEN;\n"
"    border-radius: 50%;\n"
"    min-width: 16px;\n"
"    min-height: 16px;\n"
"}\n"
"#modern-slider trough block.filled {\n"
"    background-color: @BOX_ON;\n"
"    border-radius: 5px;\n"
"}\n"
"#modern-slider value {\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    color: @OFF_WHITE;\n"
"}\n"
"#slider-label {\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    color: @OFF_WHITE;\n"
"}\n"
"#tx-panadapter-button {\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: @DARK_LINES;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @BOX_OFF;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"}\n"
"#tx-panadapter-button-bar {\n"
"    padding: 10px;\n"
"    background-color: @BACKGROUND;\n"
"}\n"
".label {\n"
"    border-width: 0px;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-family: FreeSans;\n"
"   strained: 0px;\n"
"}\n"
"#warning-label {\n"
"    font-family: FreeSans;\n"
"    color: @WARNING;\n"
"}";

void load_css() {
    GtkCssProvider *provider;
    GdkDisplay *display;
    GdkScreen *screen;

    g_print("%s\n", __FUNCTION__);
    provider = gtk_css_provider_new();
    display = gdk_display_get_default();
    screen = gdk_display_get_default_screen(display);
    gtk_style_context_add_provider_for_screen(screen,
                                             GTK_STYLE_PROVIDER(provider),
                                             GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);

    gtk_css_provider_load_from_data(provider, css, -1, NULL);
    g_object_unref(provider);
}